### Mulitple Linear Regression

In [8]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
df = pd.read_csv('ml_data_salary.csv')
df.head(3)

age  distance  YearsExperience  Salary
0  31.1     77.75              1.1   39343
1  31.3     78.25              1.3   46205
2  31.5     78.75              1.5   37731

In [10]:
# X is indpendent V 
X = df[['age','distance','YearsExperience']]
#y is dependent V
y=df[['Salary']]

In [11]:
X.head()

age  distance  YearsExperience
0  31.1     77.75              1.1
1  31.3     78.25              1.3
2  31.5     78.75              1.5
3  32.0     80.00              2.0
4  32.2     80.50              2.2

In [12]:
y.head()

Salary
0   39343
1   46205
2   37731
3   43525
4   39891

In [15]:
# create and fit your model 
model =LinearRegression().fit(X,y)
model

LinearRegression()

In [16]:
model.coef_

array([[-3.00216193e+15,  1.18788781e+15,  3.24424072e+13]])

In [17]:
model.intercept_

array([9.73272215e+14])

In [19]:
model.predict([[31.1,77.75,1.1]])

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36208.875]])

In [20]:
model.score(X,y)

0.9569687392667418